# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hemanthr/hemanth/corundum/fpga/lib/eth/example/ZCU102/fpga/fpga/fpga.srcs/sources_1/ip/eth_xcvr_gt_channel/eth_xcvr_gt_channel.xci
# IP: The module: 'eth_xcvr_gt_channel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hemanthr/hemanth/corundum/fpga/lib/eth/example/ZCU102/fpga/fpga/fpga.gen/sources_1/ip/eth_xcvr_gt_channel/synth/eth_xcvr_gt_channel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_xcvr_gt_channel'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hemanthr/hemanth/corundum/fpga/lib/eth/example/ZCU102/fpga/fpga/fpga.gen/sources_1/ip/eth_xcvr_gt_channel/synth/eth_xcvr_gt_channel.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_xcvr_gt_channel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hemanthr/hemanth/corundum/fpga/lib/eth/example/ZCU102/fpga/fpga/fpga.srcs/sources_1/ip/eth_xcvr_gt_channel/eth_xcvr_gt_channel.xci
# IP: The module: 'eth_xcvr_gt_channel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hemanthr/hemanth/corundum/fpga/lib/eth/example/ZCU102/fpga/fpga/fpga.gen/sources_1/ip/eth_xcvr_gt_channel/synth/eth_xcvr_gt_channel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_xcvr_gt_channel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hemanthr/hemanth/corundum/fpga/lib/eth/example/ZCU102/fpga/fpga/fpga.gen/sources_1/ip/eth_xcvr_gt_channel/synth/eth_xcvr_gt_channel.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_xcvr_gt_channel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
