# vim: syntax=make
include .config

DOLPHIN_PATH := $(CONFIG_POPCORN_KMSG_DOLPHIN_DIS_PATH)

ccflags-y := \
	-I$(DOLPHIN_PATH)/src/IRM_GX/drv/src \
	-I$(DOLPHIN_PATH)/src/IRM_GX/drv/src/LINUX \
	-I$(DOLPHIN_PATH)/src/COMMON/osif/kernel/include \
	-I$(DOLPHIN_PATH)/src/COMMON/osif/kernel/include/LINUX \
	-I$(DOLPHIN_PATH)/src/include/ \
	-I$(DOLPHIN_PATH)/src/include/dis/ \
	-I$(DOLPHIN_PATH)/include

ccflags-y += -D_KERNEL
ccflags-y += -DOS_IS_LINUX
#ccflags-y += -DENABLE_DMA
#ccflags-y += -DPROF_HISTOGRAM
#ccflags-y += -DTEST_MSG_LAYER
#ccflags-y += -DTEST_MSG_LAYER_SERVER

KBUILD_EXTRA_SYMBOLS := $(DOLPHIN_PATH)/src/IRM_GX/drv/src/LINUX/Module.symvers

obj-$(CONFIG_POPCORN_KMSG_DOLPHIN) += msg_dolphin.o
