obj-$(CONFIG_POPCORN)	+= init.o util.o
obj-$(CONFIG_POPCORN)	+= wait_station.o
obj-$(CONFIG_POPCORN)	+= sched_server.o process_server.o vma_server.o
obj-$(CONFIG_POPCORN)	+= page_server.o
obj-$(CONFIG_POPCORN)	+= bundle.o
obj-$(CONFIG_POPCORN)	+= remote_info.o
obj-$(CONFIG_POPCORN)	+= pcn_kmsg.o
obj-$(CONFIG_POPCORN_STAT)	+= stat.o

#obj-$(CONFIG_POPCORN) +=  futex_remote.o global_spinlock.o remote_file.o
