obj-$(CONFIG_POPCORN)	+= init.o util.o
obj-$(CONFIG_POPCORN)	+= wait_station.o
obj-$(CONFIG_POPCORN)	+= sched_server.o process_server.o vma_server.o
obj-$(CONFIG_POPCORN)	+= page_server.o fh_action.o
obj-$(CONFIG_POPCORN)	+= bundle.o
obj-$(CONFIG_POPCORN)	+= remote_info.o
obj-$(CONFIG_POPCORN)	+= pcn_kmsg.o
obj-$(CONFIG_POPCORN)	+= stat.o
obj-$(CONFIG_POPCORN)	+= syscall_server.o

# Popcorn MVX
obj-$(CONFIG_POPCORN)	+= mvx_server.o
obj-$(CONFIG_POPCORN)	+= mvx_engine.o

obj-$(CONFIG_POPCORN_POWER_SENSOR_X86) += power_sensor_x86.o
obj-$(CONFIG_POPCORN_POWER_SENSOR_ARM) += power_sensor_arm.o

#obj-$(CONFIG_POPCORN) +=  futex_remote.o global_spinlock.o remote_file.o
