obj-$(CONFIG_POPCORN)	+= init.o cpu_namespace.o stat.o debug.o
obj-$(CONFIG_POPCORN)	+= sched_server.o process_server.o vma_server.o
 obj-$(CONFIG_POPCORN)	+= page_server.o
#obj-$(CONFIG_POPCORN) +=  futex_remote.o global_spinlock.o proc_remote.o remote_file.o
obj-$(CONFIG_POPCORN)	+= bundle.o
obj-$(CONFIG_POPCORN)	+= remote_cpu_info.o
obj-$(CONFIG_POPCORN)	+= remote_mem_info.o
